# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/:title

# Setup
title:           akbar rizqi luhur p
tagline:          'blog'
description:      'My personal blog.'
url:              http://kikicr.github.io/blogs
baseurl:          /blogs
commentsystem:    google
disqus:           example

author:
  name:           akbar rizqi luhur p
  url:            https://plus.google.com/u/0/116028509437214132130/posts

paginate:         5

# Custom vars
icon:             /blog/assets/images/icon.png
cover:            /blog/assets/images/cover.png

social:

  - icon:         github
    url:          https://github.com/kikicr
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://plus.google.com/u/0/116028509437214132130/posts
    desc:         Add me on google+


menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:        Akbar Rizqi
  url:            http://kikicr.github.io/blogs
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
